### ISSUE TITLE
Instalation process - "Stop and Back" -> ReflectionException

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/installation#2]
Steps:

1. Go through the first three steps of Web-based Installer with valid data
2. Go to step 4, and start install
3. If there will be ~68% of installation process, click "Stop and Back"
4. Then go to step 4 and start install again

Results:

ReflectionException   

https://puu.sh/wpbgX/a413375083.png

The same issue is during instalation on Ubuntu 16, but alredy at the first installation without making "stop and back".

**Comment by MarcinKozak** [comment]
@dawid-g Fixed by updating libraryversion. https://github.com/antaresproject/two_factor_auth/commit/6ff0b31d921d6713660cdcec23027e05108ccbd6
