### ISSUE TITLE
Installation process - 500 internal server error

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/installation#4]
Preconditions:
- automatic installation
- ubuntu 14

1. Make first installation stage
2. Enter YourIP/Install

Results:

https://image.prntscr.com/image/4R1A1t3RSoC8gXLDkfJXjQ.png

**Comment by mountstone** [comment]
@dawid-g Master branch has been updated.

**Comment by dawid-g** [comment]
verified as fixed.
