### ISSUE TITLE
"Stop and Back" during installation process - 404 page not found

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/installation#5]
If I click on the 4th step of installation (4. Install Antares) "Stop and Back", there is displayed error "404 Page Not Found".

https://image.prntscr.com/image/VKx-d1U4SDqyZrGqB40Oug.png

**Comment by mountstone** [comment]
@dawid-g Unable to repeat the error. Are you sure your server env. is configured correctly?

**Comment by dawid-g** [comment]
It is better, but I have a similar problem. I clicked Stop and Back during installation, then I run the installation in step 4 again and clicked Stop and Back again (It was on 38% loading).


Results:
https://image.prntscr.com/image/S_aWuzG3TEisXVTl2cUzVw.png

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
68% installation, stop and back: https://image.prntscr.com/image/0cLR24e8RWWpl0m7EFnexA.png

**Comment by mountstone** [comment]
@dawid-g When installation progress has more than 30% of sophistication, **installation cannot be stoped**. The button called "Stop and back" should be removed. 

Install fresh app and refresh browser cache, please.
