### ISSUE TITLE
[Manual] "Your requirements could not be resolved" during "composer create-project"

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/installation#6]
Preconditions: 
- Ubuntu 14

During manual installation according to the documentation, on step "composer create-project antaresproject/project /var/www/html dev-master --keep-vcs"

There is displayed error: 

https://image.prntscr.com/image/M13PfwviShKLSdFtIMAcOg.png
It is possible to resolve this problem, but it is not quite good If user must resolving problems during installation.

**Comment by mountstone** [comment]
@dawid-g Unable to repeat the error. 

Are you sure your server env is configured correctly?

**Comment by dawid-g** [comment]
It's ok now, closed.
